% LIB
%
% Files
%   Bragg_peak           - Bragg_peak.m
%   ConditionDopRWIC     - ConditionDopRWIC.m
%   createfigure4x2      - createfigure4x2(X1a,Y1a,X2a,Y2a,X1b,Y1b,X2b,Y2b,X1c,Y1c,X2c,Y2c,X1d,Y1d,X2d,Y2d,X1e,Y1e,X2e,Y2e,X1f,Y1f,X2f,Y2f,X1g,Y1g,X2g,Y2g,X1h,Y1h,X2h,Y2h)
%   createfigure4x2ab    - createfigure4x2(X1a,Y1a,X2a,Y2a,X1b,Y1b,X2b,Y2b,X1c,Y1c,X2c,Y2c,X1d,Y1d,X2d,Y2d,X1e,Y1e,X2e,Y2e,X1f,Y1f,X2f,Y2f,X1g,Y1g,X2g,Y2g,X1h,Y1h,X2h,Y2h)
%   createfigure4x2clean - Auto-generated by MATLAB on 08-Feb-2019 17:37:35
%   Gauss_fit            - Gauss_fit.m
%   hfr_noise            - hfr_noise.m
%   findSwellRWIC        - findSwellRWIC.m (calls internal: swellpeak.m)
%   invWindRWIC          - invWindRWIC.m
%   plot_swell           - plot_swell
%   plot_wind            - plot_wind.m
%   PXYint               - PXYint.m
%   PXYsideband          - PXYsideband.m
%   specSwellRWIC        - specSwellRWIC.m
%   spectral_noise       - spectral_noise.m
%   specWindRWIC         - specWindRWIC.m
%   subplot_spec4x2      - Use value nplot to assign letter symbol (A to H)
%   subplot_spec4x2ab    - Use value nplot to assign letter symbol (A to H)
%   waveparams           - waveparams.m
%   weightf_barrick      - weightf_barrick.m
%   wn2ndRWIC            - wn2ndRWIC.m
%   wspecRWIC            - wspecRWIC.m
