function createfigure4x2(X1a,Y1a,X2a,Y2a,X1b,Y1b,X2b,Y2b,X1c,Y1c,X2c,Y2c,X1d,Y1d,X2d,Y2d,X1e,Y1e,X2e,Y2e,X1f,Y1f,X2f,Y2f,X1g,Y1g,X2g,Y2g,X1h,Y1h,X2h,Y2h)
%createfigure4x2(X1a,Y1a,X2a,Y2a,X1b,Y1b,X2b,Y2b,X1c,Y1c,X2c,Y2c,X1d,Y1d,X2d,Y2d,X1e,Y1e,X2e,Y2e,X1f,Y1f,X2f,Y2f,X1g,Y1g,X2g,Y2g,X1h,Y1h,X2h,Y2h)

%  Auto-generated by MATLAB on 08-Feb-2019 17:37:35

% Create figure
figure('InvertHardcopy','off','Color',[1 1 1],...
    'OuterPosition',[593.8 -9.4 542.4 864]);

% Create axes
axes1 = axes('Position',[0.09 0.765 0.44 0.215]);
hold(axes1,'on');

% Create loglog
loglog(X1a,Y1a,'MarkerSize',8,'LineWidth',1,'Color',[0 0 1]);
% Create loglog
loglog(X2a,Y2a,'MarkerSize',8,'LineWidth',1,'Color',[1 0 0]);
a4 = 1.1*(.25^4);
a5 = 1.1*(.25^5);
loglog([0.15 0.5],a4*[0.15 0.5].^(-4))
loglog([0.15 0.5],a5*[0.15 0.5].^(-5))

% Create text
text('LineWidth',1,'FontName','arial','String','A','Position',[0.055 20 0]);

% Create ylabel
ylabel('S(f) (m^{2}/Hz)','LineWidth',1,'FontName','arial');
%===========================================================================
% Uncomment the following line to preserve the X-limits of the axes
 xlim(axes1,[0.052 0.5]);
% Uncomment the following line to preserve the Y-limits of the axes
 ylim(axes1,[0.003 50]);
% Uncomment the following line to preserve the Z-limits of the axes
 zlim(axes1,[-1 1]);
box(axes1,'on');
grid(axes1,'on');
% Set the remaining axes properties
set(axes1,'FontName','arial','GridAlpha',1,'GridColor',[0.8 0.8 0.8],...
    'GridLineStyle',':','LineWidth',1,'TickDir','out','TickLength',[0.01 0.01],...
    'XMinorGrid','on','XMinorTick','on','XScale','log','XTickLabel',{},...
    'YMinorTick','on','YScale','log');

% Create axes
axes2 = axes('Position',[0.09 0.53 0.44 0.215]);
hold(axes2,'on');

% Create loglog
loglog(X1b,Y1b,'MarkerSize',8,'LineWidth',1,'Color',[0 0 1]);
% Create loglog
loglog(X2b,Y2b,'MarkerSize',8,'LineWidth',1,'Color',[1 0 0]);

loglog([0.15 0.5],a4*[0.15 0.5].^(-4))
loglog([0.15 0.5],a5*[0.15 0.5].^(-5))

% Create text
text('LineWidth',1,'FontName','arial','String','B','Position',[0.055 20 0]);
% Create ylabel
ylabel('S(f) (m^{2}/Hz)','LineWidth',1,'FontName','arial');

% Uncomment the following line to preserve the X-limits of the axes
xlim(axes2,[0.052 0.5]);
% Uncomment the following line to preserve the Y-limits of the axes
 ylim(axes2,[0.003 50]);
% Uncomment the following line to preserve the Z-limits of the axes
 zlim(axes2,[-1 1]);
box(axes2,'on');
grid(axes2,'on');
% Set the remaining axes properties
set(axes2,'FontName','arial','GridAlpha',1,'GridColor',[0.8 0.8 0.8],...
    'GridLineStyle',':','LineWidth',1,'TickDir','out','TickLength',[0.01 0.01],...
    'XMinorGrid','on','XMinorTick','on','XScale','log','XTickLabel',{},...
    'YMinorTick','on','YScale','log');





% Create axes
axes3 = axes('Position',[0.09 0.295 0.44 0.215]);
hold(axes3,'on');

% Create loglog
loglog(X1c,Y1c,'MarkerSize',8,'LineWidth',1,'Color',[0 0 1]);
% Create loglog
loglog(X2c,Y2c,'MarkerSize',8,'LineWidth',1,'Color',[1 0 0]);
loglog([0.15 0.5],a4*[0.15 0.5].^(-4))
loglog([0.15 0.5],a5*[0.15 0.5].^(-5))

% Create text
text('LineWidth',1,'FontName','arial','String','C','Position',[0.055 20 0]);

% Create ylabel
ylabel('S(f) (m^{2}/Hz)','LineWidth',1,'FontName','arial');

% Uncomment the following line to preserve the X-limits of the axes
 xlim(axes3,[0.052 0.5]);
% Uncomment the following line to preserve the Y-limits of the axes
 ylim(axes3,[0.003 50]);
% Uncomment the following line to preserve the Z-limits of the axes
 zlim(axes3,[-1 1]);
box(axes3,'on');
grid(axes3,'on');
% Set the remaining axes properties
set(axes3,'FontName','arial','GridAlpha',1,'GridColor',[0.8 0.8 0.8],...
    'GridLineStyle',':','LineWidth',1,'TickDir','out','TickLength',[0.01 0.01],...
    'XMinorGrid','on','XMinorTick','on','XScale','log','XTickLabel',{},...
    'YMinorTick','on','YScale','log');

% Create axes
axes4 = axes('Position',...
    [0.0881060606060606 0.0600000000000001 0.440000000000001 0.215]);
hold(axes4,'on');

% Create loglog
loglog(X1d,Y1d,'MarkerSize',8,'LineWidth',1,'Color',[0 0 1]);
% Create loglog
loglog(X2d,Y2d,'MarkerSize',8,'LineWidth',1,'Color',[1 0 0]);% Create text
loglog([0.15 0.5],a4*[0.15 0.5].^(-4))
loglog([0.15 0.5],a5*[0.15 0.5].^(-5))

text('LineWidth',1,'FontName','arial','String','D','Position',[0.055 20 0]);
% Create ylabel
ylabel('S(f) (m^{2}/Hz)','LineWidth',1,'FontName','arial');

% Create xlabel
xlabel('f (Hz)','LineWidth',1,'FontName','arial');

% Uncomment the following line to preserve the X-limits of the axes
 xlim(axes4,[0.052 0.5]);
% Uncomment the following line to preserve the Y-limits of the axes
 ylim(axes4,[0.003 50]);
% Uncomment the following line to preserve the Z-limits of the axes
 zlim(axes4,[-1 1]);
box(axes4,'on');
grid(axes4,'on');
% Set the remaining axes properties
set(axes4,'FontName','arial','GridAlpha',1,'GridColor',[0.8 0.8 0.8],...
    'GridLineStyle',':','LineWidth',1,'TickDir','out','TickLength',[0.01 0.01],...
    'XMinorGrid','on','XMinorTick','on','XScale','log','YMinorTick','on',...
    'YScale','log');


% Create axes
axes5 = axes('Position',[0.542424242424242 0.765 0.44 0.215]);
hold(axes5,'on');

% Create loglog
loglog(X1e,Y1e,'MarkerSize',8,'LineWidth',1,'Color',[0 0 1]);
% Create loglog
loglog(X2e,Y2e,'MarkerSize',8,'LineWidth',1,'Color',[1 0 0]);
loglog([0.15 0.5],a4*[0.15 0.5].^(-4))
loglog([0.15 0.5],a5*[0.15 0.5].^(-5))

% Create text
text('LineWidth',1,'FontName','arial','String','E','Position',[0.055 20 0]);

% Uncomment the following line to preserve the X-limits of the axes
 xlim(axes5,[0.052 0.5]);
% Uncomment the following line to preserve the Y-limits of the axes
 ylim(axes5,[0.003 50]);
% Uncomment the following line to preserve the Z-limits of the axes
 zlim(axes5,[-1 1]);
box(axes5,'on');
grid(axes5,'on');
% Set the remaining axes properties
set(axes5,'FontName','arial','GridAlpha',1,'GridColor',[0.8 0.8 0.8],...
    'GridLineStyle',':','LineWidth',1,'TickDir','out','TickLength',[0.01 0.01],...
    'XMinorGrid','on','XMinorTick','on','XScale','log','XTickLabel',{},...
    'YMinorTick','on','YScale','log','YTickLabel',{});
% Create legend
legend('in situ','inversion','f^{-4}','f^{-5}')
legend1 = legend(axes5,'show');
set(legend1,...
    'Position',[0.0905188453505348 0.773758279572319 0.228409094051881 0.0897468983634445],...
    'LineWidth',1,...
    'FontSize',10);

% Create axes
axes6 = axes('Position',[0.542424242424242 0.53 0.44 0.215]);
hold(axes6,'on');
% Create loglog
loglog(X1f,Y1f,'MarkerSize',8,'LineWidth',1,'Color',[0 0 1]);
% Create loglog
loglog(X2f,Y2f,'MarkerSize',8,'LineWidth',1,'Color',[1 0 0]);
loglog([0.15 0.5],a4*[0.15 0.5].^(-4))
loglog([0.15 0.5],a5*[0.15 0.5].^(-5))

% Create text
text('LineWidth',1,'FontName','arial','String','F',...
    'Position',[0.0545724120299138 19.9999983917881 0]);
% Uncomment the following line to preserve the X-limits of the axes
xlim(axes6,[0.052 0.5]);
ylim(axes6,[0.003 50]);
zlim(axes6,[-1 1]);
box(axes6,'on');
grid(axes6,'on');
% Set the remaining axes properties
set(axes6,'FontName','arial','GridAlpha',1,'GridColor',[0.8 0.8 0.8],...
    'GridLineStyle',':','LineWidth',1,'TickDir','out','TickLength',[0.01 0.01],...
    'XMinorGrid','on','XMinorTick','on','XScale','log','XTickLabel',{},...
    'YMinorTick','on','YScale','log','YTickLabel',{});



% Create axes
axes7 = axes('Position',[0.542424242424242 0.295 0.44 0.215]);
hold(axes7,'on');
% Create loglog
loglog(X1g,Y1g,'MarkerSize',8,'LineWidth',1,'Color',[0 0 1]);
% Create loglog
loglog(X2g,Y2g,'MarkerSize',8,'LineWidth',1,'Color',[1 0 0]);% Create text
loglog([0.15 0.5],a4*[0.15 0.5].^(-4))
loglog([0.15 0.5],a5*[0.15 0.5].^(-5))


text('LineWidth',1,'FontName','arial','String','G','Position',[0.055 20 0]);

% Uncomment the following line to preserve the X-limits of the axes
 xlim(axes7,[0.052 0.5]);
% Uncomment the following line to preserve the Y-limits of the axes
 ylim(axes7,[0.003 50]);
% Uncomment the following line to preserve the Z-limits of the axes
 zlim(axes7,[-1 1]);
box(axes7,'on');
grid(axes7,'on');
% Set the remaining axes properties
set(axes7,'FontName','arial','GridAlpha',1,'GridColor',[0.8 0.8 0.8],...
    'GridLineStyle',':','LineWidth',1,'TickDir','out','TickLength',[0.01 0.01],...
    'XMinorGrid','on','XMinorTick','on','XScale','log','XTickLabel',{},...
    'YMinorTick','on','YScale','log','YTickLabel',{});


% Create axes
axes8 = axes('Position',[0.542424242424242 0.06 0.44 0.215]);
hold(axes8,'on');

% Create loglog
loglog(X1h,Y1h,'MarkerSize',8,'LineWidth',1,'Color',[0 0 1]);
% Create loglog
loglog(X2h,Y2h,'MarkerSize',8,'LineWidth',1,'Color',[1 0 0]);% Create text
loglog([0.15 0.5],a4*[0.15 0.5].^(-4))
loglog([0.15 0.5],a5*[0.15 0.5].^(-5))

text('LineWidth',1,'FontName','arial','String','H','Position',[0.055 20 0]);
xlim(axes8,[0.052 0.5]);
ylim(axes8,[0.003 50]);
zlim(axes8,[-1 1]);
box(axes8,'on');
grid(axes8,'on');
% Set the remaining axes properties
set(axes8,'FontName','arial','GridAlpha',1,'GridColor',[0.8 0.8 0.8],...
    'GridLineStyle',':','LineWidth',1,'TickDir','out','TickLength',[0.01 0.01],...
    'XMinorGrid','on','XMinorTick','on','XScale','log','YMinorTick','on',...
    'YScale','log','YTickLabel',{});
